name: Sync to Bitbucket

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "cuteys"
        git config --global user.email "117161372+cuteys@users.noreply.github.com"

    - name: Add Bitbucket remote
      run: |
        git remote remove bitbucket || true
        git remote add bitbucket https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/cuteys_king/vpn_tool.git

    - name: Fetch all branches from Bitbucket
      run: git fetch --all

    - name: Pull and push all branches
      run: |
        for remote_branch in $(git ls-remote --heads bitbucket | awk '{print $2}'); do
          branch=${remote_branch#refs/heads/}
          git checkout $branch || git checkout -b $branch
          git pull bitbucket $branch --rebase
          git push bitbucket $branch
        done

    - name: Push all tags to Bitbucket
      run: git push bitbucket --tags
