name: Sync to GitLab

on:
  push:
    branches:
      - main  # 或其他你希望同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote remove gitlab || true
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/wmystc/script.git

    - name: Push all branches and tags to GitLab
      run: |
        git push gitlab --all
        git push gitlab --tags
